### ISSUE TITLE
User/PW -> Error 403

### ISSUE THREAD

**Issue by vr6syncro** [BasGo/ioBroker.egigeozone#1]
Wenn  man einen User und PW eingibt kommt immer die 403 Error meldung. Nur wenn man beides weg macht klappt die Verbindung. Irgendwo ist da der Wurm drin. Habe schon mehrfach andere Kombis probiert alles ohne Erfolg.
`egigeozone.0   2017-10-02 22:50:09.080   warn   User credentials invalid
egigeozone.0   2017-10-02 22:50:09.080   debug   Decoded authorization
egigeozone.0   2017-10-02 22:50:09.079   debug   Authorization header is:`

**Comment by BasGo** [comment]
Fehler sollte mit der Version 0.1.0 behoben sein: es gab einen kleinen Typo bei der Prüfung.
