### ISSUE TITLE
States "atHome" und "atHomeCount" werden nicht gefüllt

### ISSUE THREAD

**Issue by SebastianSchultz** [BasGo/ioBroker.egigeozone#2]
Die States "atHome" und "atHomeCount" werden nicht gefüllt.
Bei beiden steht bei mir immer "0" drin.

**Comment by BasGo** [comment]
Hi Sebastian,

enthält die URL, die du bei EgiGeoZone hinterlegt hast, einen Namen? Die URL sollte mit dem folgenden Schema aufgebaut sein:

http://deine-domain:1234/**Max** bzw. https://deine-domain:1234/**Max**

Auf diese Weise würde **Max** bei atHome gesetzt werden, sofern er die Home-Zone betritt. Habe dies gerade auch noch mal mit Erfolg nachtesten können. Wenn jedoch kein Name hinterlegt ist, dann funktioniert der Mechanismus nicht.

Da dieser Hinweis fehlt, werde ich ihn in der README ergänzen.

**Comment by SebastianSchultz** [comment]
Hallo,
bei mir wird der Name ohne Sterne hinter dem letzten Slash übergeben.Ist dss evtl. schon die Ursache???


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: BasGo <notifications@github.com> Datum: 06.10.17  20:16  (GMT+01:00) An: "BasGo/ioBroker.egigeozone" <ioBroker.egigeozone@noreply.github.com> Cc: Sebastian Schultz <mail@sebastian-schultz.de>, Author <author@noreply.github.com> Betreff: Re: [BasGo/ioBroker.egigeozone] States "atHome" und "atHomeCount" werden nicht gefüllt (#2) 
Hi Sebastian,
enthält die URL, die du bei EgiGeoZone hinterlegt hast, einen Namen? Die URL sollte mit dem folgenden Schema aufgebaut sein:
http://deine-domain:1234/**Max** bzw. https://deine-domain:1234/**Max**
Auf diese Weise würde Max bei atHome gesetzt werden, sofern er die Home-Zone betritt. Habe dies gerade auch noch mal mit Erfolg nachtesten können. Wenn jedoch kein Name hinterlegt ist, dann funktioniert der Mechanismus nicht.
Da dieser Hinweis fehlt, werde ich ihn in der README ergänzen.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BasGo/ioBroker.egigeozone","title":"BasGo/ioBroker.egigeozone","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BasGo/ioBroker.egigeozone"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BasGo in #2: Hi Sebastian,\r\n\r\nenthält die URL, die du bei EgiGeoZone hinterlegt hast, einen Namen? Die URL sollte mit dem folgenden Schema aufgebaut sein:\r\n\r\nhttp://deine-domain:1234/**Max** bzw. https://deine-domain:1234/**Max**\r\n\r\nAuf diese Weise würde **Max** bei atHome gesetzt werden, sofern er die Home-Zone betritt. Habe dies gerade auch noch mal mit Erfolg nachtesten können. Wenn jedoch kein Name hinterlegt ist, dann funktioniert der Mechanismus nicht.\r\n\r\nDa dieser Hinweis fehlt, werde ich ihn in der README ergänzen.\r\n\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/BasGo/ioBroker.egigeozone/issues/2#issuecomment-334831639"}}}

**Comment by SebastianSchultz** [comment]
Hier mal ein Auszug aus der Objektübersicht vom ioBroker.
Meine Frau und ich sind zu Hause, aber bei "atHome" steht nix :(
![unbenannt](https://user-images.githubusercontent.com/12255583/31312071-96f9a0fc-abba-11e7-93f2-00a6177a886c.png)

**Comment by BasGo** [comment]
Der Name muss natürlich ohne Sternchen angegeben werden, diese sollten nur der Formatierung (hier bei GitHub) dienen. Heißt also, eine "richtige" URL sähe so aus: http://deine-domain:1234/Max

Warum aber der atHome-Status nicht aktualisiert wird, kann ich mir im Moment nicht erklären: ich hatte es am WE mehrfach getestet und bei mir hat es immer wunderbar funktioniert. Eine Idee wäre vielleicht noch, dass das Leerzeichen in deinem "Zu Hause" stören könnte oder aber auch, dass der in der Konfiguration hinterlegte Wert für Zuhause vllt. ein überflüssiges Leerzeichen am Anfang oder Ende hat? Könntest du mal versuchen, anstelle von "Zu Hause" ein einfach "zuhause" zu verwenden?

Ich würde parallel gucken, dass ich im Adapter ein paar Vorkehrungen treffe, so dass solche textuellen Dinge die Funktion nicht beeinträchtigen sollten. Die Änderung käme dann mit der nächsten Version ;-)

**Comment by BasGo** [comment]
Für eventuelle Leerzeichen am Anfang oder Ende der "Zuhause"-Lokation gibt es eine entsprechende Bereinigung in Version 0.1.1

**Comment by SebastianSchultz** [comment]
Ich mal wieder :)
Problem erkannt. Es lag wirklich am Leerzeichen zwischen "Zu" und "Hause". "Zuhause" funktioniert.
Vielleicht sollte man das Adapterkonfiguration unterbinden, dass Leerzeichen eingegeben werden können :)
